---
- name: Copy the environment file for rally
  shell: source openrc admin demo
  become: true
  become_user: stack
  args:
    chdir: /opt/stack/devstack

- name: Copy the Neutron create network scenario
  template:
    src: 
    dest:
  become: true
  become_user: stack

#- name: Create rally database
#  shell: rally db create
#  become: true
#  become_user: stack

#- name: Waiting some seconds
#  pause: seconds=10

- name: Install urllib3 to 1.24.2 version pip
  pip:
    name: urllib3
  become: true

- name: Install urllib3 to 1.24.2 version pip3 
  pip:
    executable: pip3
    name: urllib3
  become: true

- name: Restart OpenStack deployment services
  shell: systemctl restart devstacl@*
  become: true
  become_user: stack

- name: Create rally environment with file
  shell: rally env create --fromenv --name openstack
  args:
    chdir: /opt/stack/
  become: true
  become_user: stack
  
