---
- name: Installing open-vswitch service
  apt: 
    name: openvswitch-switch
  become: true

- name: Update python alternative
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3.6
  become: true
 
- name: Check the IP address of the machines
  register: ip_eno1
  shell: ip a | grep eno1 | grep inet | cut -d/ -f1 | cut -d ' ' -f6- 
  ignore_errors: true

- name: Add stack user
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    system: yes

- name: Make stack user a sudoer
  lineinfile:
    dest: /etc/sudoers.d/stack
    line: "stack ALL=(ALL) NOPASSWD: ALL"
    create: yes

- name: Download Devstack Stein
  git:
    dest: /opt/stack/devstack
    repo: https://git.openstack.org/openstack-dev/devstack
    version: stable/stein
    force: yes
    update: no
    depth: 1
  become: true
  become_user: stack

- name: Unstack action
  shell: /opt/stack/devstack/unstack.sh &> /tmp/unstack-logs
  args:
    executable: /bin/bash
  become: true
  become_user: stack
  register: result
  until: result is succeeded
  retries: 1

- name: Fixing the problem with pip2.7 part I
  shell: wget https://bootstrap.pypa.io/get-pip.py
  ignore_errors: true
  args:
    chdir: /opt/stack/
  become: true

- name: Fixing the problem with pip2.7 part II
  shell: python2.7 get-pip.py
  ignore_errors: true
  args:
    chdir: /opt/stack/
  become: true

- name: Create the devstack local.conf
  template:
    src: local.conf.tpl
    dest: /opt/stack/devstack/local.conf
    owner: stack
  become: true
  become_user: stack

- name: Create folder for local OpenStack repository
  shell: mkdir tmp
  become: true
  args:
    chdir: /opt/
  ignore_errors: true

- name: Give permissions to the folder
  shell: chmod 777 -R /opt/tmp
  become: true

- name: Download glance from front-end
  synchronize:
    src: /home/daespinel/public/glance
    dest: /opt/tmp/
  become: true

- name: Download heat from front-end
  synchronize:
    src: /home/daespinel/public/heat
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download horizon from front-end
  synchronize:
    src: /home/daespinel/public/horizon
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download keystone from front-end
  synchronize:
    src: /home/daespinel/public/keystone
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download networking-bagpipe from front-end
  synchronize:
    src: /home/daespinel/public/networking-bagpipe
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download networking-bgpvpn from front-end
  synchronize:
    src: /home/daespinel/public/networking-bgpvpn
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download neutron from front-end
  synchronize:
    src: /home/daespinel/public/neutron
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download noVNC from front-end
  synchronize:
    src: /home/daespinel/public/noVNC
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download placement from front-end
  synchronize:
    src: /home/daespinel/public/placement
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download rally from front-end
  synchronize:
    src: /home/daespinel/public/rally
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download requirements from front-end
  synchronize:
    src: /home/daespinel/public/requirements
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Download nova from front-end
  synchronize:
    src: /home/daespinel/public/nova
    dest: /opt/tmp/
  become: true
  become_user: stack

- name: Adding the br-mpls bridge
  shell: ovs-vsctl add-br br-mpls
  become: true
  ignore_errors: true

- name: Copy the modified neutron-lib file to the deployment
  template:
    src: interconnection.py.tpl
    dest: /opt/stack/interconnection.py
    owner: stack
  become: true
  become_user: stack

- name: Modify neutron stack script to add new file for neutron-lib neutron
  template:
    src: neutron.tpl
    dest: /opt/stack/devstack/lib/neutron
    owner: stack
  become: true
  become_user: stack

- name: Copy the in-deployment created list of openstack hosts
  template:
    src: os_list.txt.tpl
    dest: /opt/stack/os_list.txt
    owner: stack
  become: true
  become_user: stack

- name: Modify neutron stack script to add new file for neutron-lib neutron-legacy
  template:
    src: neutron-legacy.tpl
    dest: /opt/stack/devstack/lib/neutron-legacy
    owner: stack
  become: true
  become_user: stack

- name: Create heat etc folder
  shell: mkdir /etc/heat/
  become: true
  ignore_errors: true

- name: Give permissions to the folder
  shell: chmod 777 -R /etc/heat/
  become: true

- name: Follow Devstack deployment
  debug:
    msg: 
      - "Follow deployment with: "
      - "ssh -l root {{ip_eno1.stdout}} tail -f /tmp/stack-logs"

- name: Run parallel Devstack installations
  shell: /opt/stack/devstack/stack.sh &> /tmp/stack-logs
  args:
    executable: /bin/bash
  become: true
  become_user: stack
  register: result
  until: result is succeeded
  retries: 1
  async: 2000
  poll: 40

- name: Download Neutron python-neutronclient
  git:
    dest: /opt/stack/python-neutronclient
    repo: "https://daespinel:MimasTitanBarcoMazda.123@github.com/daespinel/python-neutronclient-1.git"
    version: stable/stein
    force: yes
    update: no
    depth: 1
  become: true
  become_user: stack

- name: Install some Packages
  apt:
    name: "{{ packages }}"
  become: true
  register: installation
  until: installation is succeeded
  retries: 30
  vars:
    packages:
      - git
      - python-pip
      - python3-pip

- name: Uninstall former python-neutronclient pip package for python2
  pip:
    name: python-neutronclient
    state: absent
  become: true

- name: Uninstall former python-neutronclient pip package for python3
  pip:
    executable: pip3
    name: python-neutronclient
    state: absent
  become: true

- name: Install the new python client
  shell: python setup.py install
  become: true
  ignore_errors: false
  args:
    chdir: /opt/stack/python-neutronclient/

- name: Install the new python client for python3
  shell: python3 setup.py install
  become: true
  ignore_errors: false
  args:
    chdir: /opt/stack/python-neutronclient/

- name: Adding additional data to neutron db min
  blockinfile:
    path: /opt/stack/neutron/neutron/db/common_db_mixin.py
    block: |4
            @staticmethod
            def _filter_non_model_columns(data, model):
                return db_utils.filter_non_model_columns(data, model)
  become: true

- name: Register the rttns values
  shell: "cat /etc/neutron/neutron.conf | grep bgpvpn_rtnn | grep -oP '\\[\\K[^\\]]+'"
  register: rtnns
  become: true

- name: Fixing the bgp rtnn issue
  lineinfile:
    dest: /etc/neutron/neutron.conf
    regexp: 'bgpvpn_rtnn = \[(.+), (.+)\]'
    line: 'bgpvpn_rtnn = {{rtnns.stdout}}'
    backrefs: yes
  become: true

- name: Restart Devstack deployment
  shell: systemctl restart devstack@*
  become: true

- name: Copy Heat template to create the networks and subnetworks
  template:
    src: heat.hot.tpl
    dest: /opt/stack/devstack/heat.hot
    owner: stack
  become: true
