---

#### TASKS for the distributed module

- name: Download DIMINET code                
  git:
    dest: /opt/stack/intersite           
    repo: "https://daespinel:MimasTitanBarcoMazda.123@github.com/daespinel/intersite.git"
    version: master
#    version: 82261c2da014482746a76b0a2cc897ee67c992a1 #L3 version
#    version: 5fcab41dc14d2432404255c2f3b90248cfcf2f69 #L2 version
    force: yes
    update: no
    depth: 1
  become: true

- name: Install the DIMINET pip requirements
  pip:
    executable: pip3        
    requirements: requirements.txt
  become: true
  ignore_errors: false
  become_user: stack
  args:
    chdir: /opt/stack/intersite/

- name: Copy the file for service.config init
  template:
    src: services.config.tpl
    dest: /opt/stack/intersite/config/services.config
  become: true

- name: Stop the DIMINET daemon (just in case)
  shell: systemctl stop intersite
  become: true
  ignore_errors: true

- name: Change mod to 777
  shell: chmod 777 -R /opt/stack/intersite/
  become: true

- name: Copy the systemd unit service file for DIMINET daemon
  template:
    src: intersite.service.tpl
    dest: /etc/systemd/system/intersite.service
  become: true

- name: Reload daemons
  shell: systemctl daemon-reload
  become: true

- name: Create database for DIMINET
  shell: python3 build_database.py
  args:
    chdir: /opt/stack/intersite/
  become: true
  become_user: stack

- name: Start DIMINET daemon
  shell: systemctl restart intersite
  become: true

- name: Copy the python file to patch endpoints
  template:
    src: endpoints.py.tpl
    dest: /opt/stack/devstack/endpoints.py
    owner: stack
  become: true
  when: regionName == 'RegionOne'

- name: Patch the endpoint list for other regions
  shell: python3 endpoints.py
  args:
    chdir: /opt/stack/devstack/
  become: true
  become_user: stack
  when: regionName == 'RegionOne'

- name: Start heat creation of resources for the first service test (L3)
  shell: source /opt/stack/devstack/openrc admin demo && openstack stack create -t /opt/stack/devstack/heat.hot experiment-stack1
  args:
    chdir: /opt/stack/devstack/
    executable: /bin/bash
  become: true
  become_user: stack
  ignore_errors: true

- name: Unzip the python-client for DIMINET module
  shell: unzip python-client-generated.zip
  args:
    chdir: /opt/stack/intersite/
  become: true
  become: stack
  ignore_errors: true

- name: Install the python-client for DIMINET
  shell: python3 setup.py install
  args: 
    chdir: /opt/stack/intersite/python-client/
  become: true
  ignore_errors: true

- name: Create results dir in first DIMINET instance
  shell: mkdir results
  args:
    chdir: /opt/stack/intersite/tests/
  become: true
  become_user: stack
  ignore_errors: false
  when: regionName == 'RegionOne'

- name: Do a pause to let the system finish the final API calls
  pause:
    minutes: 2

- name: Copy a more actual test file
  template:
    src: test.py.tpl
    dest: /opt/stack/intersite/tests/test.py
  become: true

- name: Run multiple DIMINET test from the first instance
  shell: python3 test.py -s 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
  args:
    chdir: /opt/stack/intersite/tests/
  become: true
  become_user: stack
  ignore_errors: false
  when: regionName == 'RegionOne'

- name: Copy the intersite log
  shell: journalctl -u intersite >> log-intersite.txt
  args:
    chdir: /opt/stack/intersite/tests/results/
  become: true
  when: regionName == 'RegionOne'

- name: Register result files to copy
  shell: ls
  args:
    chdir: /opt/stack/intersite/tests/results/
  become: true
  register: files_to_copy
  when: regionName == 'RegionOne'

- name: Copy the result to the front-end
  fetch:
    src: /opt/stack/intersite/results/{{item}}
    dest: /home/daespinel/juice/test_results/results_march_26/
    mode: 0777
  become: true
  with_items: "{{files_to_copy.stdout_lines}}"
  when: regionName == 'RegionOne'
