---

#### TASKS for the distributed module

- name: Download DIMINET code                
  git:
    dest: /opt/stack/intersite           
    repo: "https://daespinel:MimasTitanBarcoMazda.123@github.com/daespinel/intersite.git"
    version: master                 
    force: yes
    update: no
    depth: 1
  become: true

- name: Install the DIMINET pip requirements
  pip:
    executable: pip3        
    requirements: requirements.txt
  become: true
  ignore_errors: false
  args:
    chdir: /opt/stack/intersite/

- name: Copy the file for service.config init
  template:
    src: services.config.tpl
    dest: /opt/stack/intersite/config/services.config
  become: true

- name: Stop the DIMINET daemon (just in case)
  shell: systemctl stop intersite
  become: true
  ignore_errors: true

- name: Change mod to 777
  shell: chmod 777 -R /opt/stack/intersite/
  become: true

- name: Copy the systemd unit service file for DIMINET daemon
  template:
    src: intersite.service.tpl
    dest: /etc/systemd/system/intersite.service
  become: true

- name: Reload daemons
  shell: systemctl daemon-reload
  become: true

- name: Create database for DIMINET
  shell: python3 build_database.py
  args:
    chdir: /opt/stack/intersite/
  become: true
  become_user: stack

- name: Start DIMINET daemon
  shell: systemctl restart intersite
  become: true

- name: Copy the python file to patch endpoints
  template:
    src: endpoints.py.tpl
    dest: /opt/stack/devstack/endpoints.py
    owner: stack
  become: true
  when: regionName == 'RegionOne'

- name: Patch the endpoint list for other regions
  shell: python3 endpoints.py
  args:
    chdir: /opt/stack/devstack/
  become: true
  when: regionName == 'RegionOne'

